server:
  port: 8084

spring:
  application:
    name: phone-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 5
      schema: samaia

eureka:
  client:
    service-url:
      defaul-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost